version: 1.0.0
database_name: animalia
base_path: /api/v1
environments:
  - MONGO_URI
roles:
  - name: First Minister
    asignations: 1
    exclude: false
  - name: Treasurer
    asignations: 1
    exclude: false
  - name: General
    asignations: 1
    exclude: false
  - name: Secretary of State
    asignations: 0
    exclude: false
  - name: Minister of State
    asignations: 0
    exclude: false
  - name: Civil
    asignations: 0
    exclude: true
